from .user import User
from .doctor import Doctor
from .nurse import Nurse
from .patient import Patient
from .availability import Availability
from .appointment import Appointment
from .vital_signs import VitalSigns
from .medical_records import MedicalRecord
from .prescriptions import Prescription
from .drugs import Drug
from .interactions import Interaction
from .specializations import Specialization
from .notification import Notification
